defaults:
  - dataset: tabula_muris
  - method: maml

model: FCNet
n_way: ???
n_shot: ???
n_query: ???

mode: train

sot: # SOT module
  enable: false
  lambda_: 10 # regularizer
  n_iters: 10
  feed_forward: false # enable the value to pass through the sot layer, by concatenation

pretrained: # Use pretrained feature extractor
  enable: false
  time: ??? # model to load
  freeze: true # freeze the layers of the feature extractor

exp:
  name: ???
  save_freq: 10
  resume: false
  seed: 42
  val_freq: 1

optimizer: Adam
lr: 0.001
optimizer_cls:
  _target_: torch.optim.${optimizer}
  lr: ${lr}

checkpoint:
  dir: checkpoints/${exp.name}/${dataset.name}/${method.name}_${model}
  test_iter: best_model
  time: latest

wandb:
  project: "sot"
  entity: "self-optimal"
  mode: "online" # Can set to offline, disabled

iter_num: 600
